import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/navBar";
import { NextUIProvider } from "@nextui-org/react";
import { IBM_Plex_Sans } from "next/font/google";

const helvetic = localFont({
  src: "./fonts/Helvetica.ttf",
  variable: "--font-helvetica",
  weight: "100 900",
});
const titles = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-titles",
});
const helveticBold = localFont({
  src: "./fonts/Helvetica-Bold.ttf",
  variable: "--font-helvetica-bold",
  weight: "100 900",
});
const aksara = localFont({
  src: "./fonts/Aksara.woff",
  variable: "--font-aksara",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helvetic.variable} ${helveticBold.variable} ${aksara.variable} ${titles.variable} antialiased`}
      >
        <NextUIProvider>
          <NavBar />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
